# Generated by Django 4.2.11 on 2024-04-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='participants',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
